# opensearch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:1.2.3
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: opensearch
