# php-fpm-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: bitnami/php-fpm:8.1.6
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: php-fpm
